version: '3.9'
services:
  react-piano:
    build:
      context: .
      # dockerfile: react.dockerfile
    volumes:
      - reactVolume:/website
      - ./website:/build/website:ro
      - ./website/node_modules:/build/website/node_modules
    ports:
      - 3002:3002
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - node-resume
  node-resume:
    build:
      context: .
      # dockerfile: Dockerfile
      dockerfile: combined.dockerfile
    ports:
      - 3003:3003
    volumes:
      - nodeVolume:/server
      - .:/build
      - ./server/node_modules:/build/server/node_modules
    environment:
      SERVER_PORT: 3003
volumes:
  reactVolume:
  nodeVolume: