version: '3.9'
services:
  react-piano:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - reactVolume:/client
      - ./client:/build/client:ro
      - ./client/node_modules:/build/client/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  reactVolume: